In [12]:
import numpy as np
arr = np.linspace(0.0, 10.0, 6).reshape(2, 3)

print(arr[1][2])

10.0


In [13]:
import numpy as np
arr = np.linspace(0.0, 10.0, 6).reshape(2, 3)
print(arr[0,1])

2.0


In [14]:
		
np.matrix(np.identity(3))

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [23]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [16]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a[:2, 1:3])

[[2 3]
 [6 7]]


In [22]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6]], dtype=np.float64)
x+y

array([[ 6.,  8.],
       [ 8., 10.]])

In [21]:
a = np.arange(0,6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

a*b

array([[ 0,  7, 16],
       [27, 40, 55]])

In [19]:
a = np.arange(0,6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [24]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
j*j

array([[0., 1.],
       [1., 0.]])

In [20]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

j.dot(j)

array([[-1.,  0.],
       [ 0., -1.]])