# data analysis:
# pandas, numpy, matplotlib (seaborn)

ML Predictive analytics
    scikitlearn

In [ ]:
import numpy as np

a = np.linspace(1, 10, 10)
print(a) #takes 3 arguments: start stop, number of points np.linspace(1, 10, 10) will make it 10 points from 1 to 10)
print(type(a))
print(type(a[0]))

#linspace is different from arange because arange takes step size as an argument
b = np.arange(1, 10, 1) # takes 3 arguments: start, stop, step size
print(b) #will make it from 1 to 10 with step size of 2
print(type(b))
print(type(b[0]))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [17]:
#this returns a 3x4 matrix with random numbers from standard normal distribution
c = np.random.randn(4) #4 is the number of elements

cc = np.random.randn(10).reshape(5,2) #reshaping it to 5 rows and 2 columns
print(c, end ="\n\n")
print(cc, end ="\n\n")

ccc = np.random.randn(10).reshape(2,5).T #reshaping it to 2 rows and 5 columns and then transposing it to 5 rows and 2 columns
print(ccc, end ="\n\n")

[0.62468374 2.0137654  1.39603324 1.05604818]

[[-0.43692734 -0.61648247]
 [ 0.54715038 -0.83299324]
 [-0.89726764 -0.64863495]
 [-1.14882642 -1.18918202]
 [-1.11851368  0.38406239]]

[[-0.59678169  2.14714911]
 [ 0.82752909 -0.45312081]
 [-0.65119523  1.46498159]
 [ 0.2157815  -0.31330937]
 [ 0.1526245   0.32501065]]



PCA: 
    single value decomposition
    eigenvalue

In [ ]:
A = np.eye(3) #identity matrix of size 3x3
print(A, end ="\n\n")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [23]:
# to find something that you don't know

?np.linalg

#this will give you the documentation of the function inv in the linalg module of numpy packag

Type:        module
String form: <module 'numpy.linalg' from '/opt/homebrew/lib/python3.11/site-packages/numpy/linalg/__init__.py'>
File:        /opt/homebrew/lib/python3.11/site-packages/numpy/linalg/__init__.py
Docstring:  
``numpy.linalg``

The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient
low level implementations of standard linear algebra algorithms. Those
libraries may be provided by NumPy itself using C versions of a subset of their
reference implementations but, when possible, highly optimized libraries that
take advantage of specialized processor functionality are preferred. Examples
of such libraries are OpenBLAS, MKL (TM), and ATLAS. Because those libraries
are multithreaded and processor dependent, environmental variables and external
packages such as threadpoolctl may be needed to control the number of threads
or specify the processor architecture.

- OpenBLAS: https://www.openblas.net/
- threadpoolctl: https://github.com/joblib/threadpoolctl

In [ ]:
#matrix multiplication
# a@b np.dot(a,b) a.dot(b)



2 ways to solve linear regression problem

analytical approach
numerical approach

#high school notation
y = a + bx

y = house price
x = house size

ml notation
y = w0 + w1 * x



take a dataset and find the w's

the set of w's {w} -> parameters, weights


given a dataset you wnt to find the best w's

your model wants to match the actual y as much as possible
    x                   y
    (size)              (actual)
1   1000                600,000
2   1200                700,000


we must define an error function:

mean squared error is an example
mse = 1/N * (sum(h_i - y_i)^2)       sum: i = 1, up to N
    we define the function as h(i) = w0 + w1 * (x^(i))                  // i is the index not a power
    y^(i) is the actual
    unknowns are w0 and w1
    mse = 1/N * (sum(w0 + w1 * x^(i) - y^(i))^2)
    find {w} that minimizes MSE
        partial derivative(J/w0) = 0
        partial derivative(J/w1) = 0
        
        #these are the functions we would get from minimizing the derivatives.
        a1w0 + b1w1 = c1
        a2w0 + b2w1 = c2
        and so we solve for the solutions to solve for w
        |a1 b1| |w0 | = |c1|
        |a2 b2| |w1 | = |c2|
        this is a matrix where A*W = C

        you want to solve for w matrix by taking the inverse so that you move something to the other size to make it W = A^-1 * C

        time complexity of matrix inversion using gaussian elimination is O(n^3)
        

        in deep learning there could be a chance to have hundreds of thousands of parameters
        is the alternative to doing the partial derivatives part? we found something called gradient descent
            machine learning can be described as gradient descent applied onto different things
            gradient descent gives you a linear way to solve things (O(n)), but it does not garuntee the best solutions
                it could be a local best solution
            gradient descent also has to assume convexity and not garunteed convergence
            problem is function J must be convex, smooth, and differentiable
            and there is something called the learning rate (step size) where you may or may not get a convergence for the step size that's not tuned (too large or too small)

            but what we can do is instead of inversing a matrix (O(n^3)) we can use gradient descent so that we can do it in O(n)
        

Mae = 1/N * (sum |h_i - y_i|)        sum: i = 1, up to M

In [ ]:
#vectorized operations
x = np.random.randn(100)

#you have an array and you want to double everything in the array
#you could use a for loop (scalar way of doing things)
y = np.zeros(100)
for i in range(100):
    y[i] = 2*x[i]
# or you could do
y = 2*x #this is vectorized operation and a better way of doing things

#the hottest model out there is the transformer model
#the trasformer model is about vectorization

#what is the full form of chatGPT?
#chat generative pre-trained transformer
#transformer is all about vectorization

In [ ]:
aa = np.random.randn(10000)
bb = np.random.randn(10000)

#what if I have to do element wise multiplication of these two arrays
dd = []
for i in range(10000):
    dd.append(aa[i]*bb[i])

#or you could do
dd = aa*bb #vectorized operation

d = np.dot(aa, bb) #this will give you the dot product of the two arrays


# microsoft c# has parallel.foreach which does vectorized operation to improve performance doing parellel execution

In [26]:
#pandas library
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
frame = pd.DataFrame(data)
print(frame.head()) #prints the first 5 rows of the dataframe
print(frame.tail()) #prints the last 5 rows of the dataframe
print(frame.shape) #prints the shape of the dataframe (number of rows and columns)
print(frame)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica
(150, 5)
     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0

In [ ]:
#with a dataframe learn how to do selection, projection, group by and aggregation
#selection: selecting rows based on some condition
print(frame[frame['species'] == 'setosa']) #selecting all rows where species is setosa
# or
frame[frame['sepal_length'] > 5.0] #selecting all rows where sepal_length is greater than 5.0
# if you do just frame['sepal_length'] > 5.0 it will return a boolean array

#projection: selecting specific columns
print(frame[['sepal_length', 'sepal_width']]) #selecting only sepal_length and sepal_width columns
#or
frame['sepal_length'][frame['sepal_length'] > 5.0] #selecting sepal_length column where sepal_length is greater than 5.0
#or
frame[frame['sepal_length'] > 5.0 & (frame['species'] == 'setosa')] #selecting sepal_length column where sepal_length is greater than 5.0 and species is setosa
#or 
frame.loc[0:2, ['sepal_length', 'species']] #selecting sepal_length and species columns for rows 0 to 2
#or
frame.iloc[0:2, [0, 4]] #selecting sepal_length and species columns for rows 0 to 2 using index
#if you type loc it will include the last index but if you type iloc it will not include the last index



#group by and aggregation: grouping by species and calculating the mean
print(frame.groupby('species').mean()) #grouping by species and calculating the mean of all other columns
print(frame.groupby('species')['sepal_length'].mean()) #grouping by species and calculating the mean of sepal_length column only

#or
#columns can be of 3 types: numerical, categorical (can you group by), text(string [not importang to us])

frame.groupby('species').mean()
frame.groupby('species')['sepal_length'].std() #standard deviation

#or
frame.groupby('species')['sepal_length'].agg([np.mean, np.std, np.min, np.max]) #aggregating multiple functions at once








frame['sepal_length'].value_counts() #gives you the count of each unique value in the sepal_length column
frame.describe() #gives you the summary statistics of the dataframe: count, mean, std, min, 25%, 50%, 75%, max for each numerical column

#find the mean of sepal_length for each species where sepal_width is greater than 3.0: this requires selection, projection, group by and aggregation
frame[frame['sepal_width'] > 3.0].groupby('species')['sepal_length'].mean()

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8         

there are 

business analysts: reports and simple data analysis

data analysts

data engineers: higher level roles with higher level analysis & higher queries
    queries would be group by and aggregation queries
    look at cross-tab queries

data scientists: higher level roles with higher level analysis & higher queries
    queries would be group by and aggregation queries
    look at cross-tab queries

ml scientists

In [ ]:
#go to profs pandas library for the class and look for the titanic dataframe 

#find the mean age of passengers that have survived = 1 grouped by Pclass

#